// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { useModel } from '@vite-umi/client';
import { AccessContext } from '@vite-umi/client';
import {useAppData} from './appData'

export function Provider(props:any) {
    const { initialState } = useModel('@@initialState');
    const access = React.useMemo(() => {
        if (typeof useAppData().umiConfig.access=="function") {
            // @ts-ignore
            return useAppData().umiConfig.access(initialState)
        }
        return useAppData().umiConfig.access
    }, [initialState]);
    return (
        <AccessContext.Provider value={access}>
            { props.children }
        </AccessContext.Provider>
    );
}

export function accessProvider(container:any) {
    return <Provider>{ container }</Provider>;
}
